name: Deploy docs to GitHub Pages

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: docs

jobs:
  deploy:
    name: Deploy docs to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Enter docs directory
        run: cd docs
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Build website
        run: npm run build
      - name: Deploy docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
